### PR TITLE
Update project Podfile for CocoaPods 1.0.1

### PR DESCRIPTION
**Pull request by apbendi**
Was seeing sporadic linker errors after upgrading to CocoaPods
1.0.1. A more aggressive refactoring of the Podfile to conform
to the 1.0+ syntax seems to have resolved the issues.

### CODE REVIEW

**Comment by marcweil** [comment]
Looks good to me. Can you be sure to update the README too to reflect Cocopods 1.0.1? Right now it's still saying 0.39.

**Comment by apbendi** [comment]
Good catch, will update

**Comment by apbendi** [comment]
Update to the README is now included, @marcweil

**Comment by marcweil** [comment]
Excellent, this all looks good to me then.

**Pull request merged**
