### PR TITLE
Changes to enable easier use with Swift

### PR DESCRIPTION
**Pull request by natevecc**
The current code base doesn't work well with Swift. You have to use a bridging header which prevents using other swift libraries that only work in cocoa pods with the `use_frameworks!` option set. By changing how `AFNetworking` is included into the project to using `@import` instead of `#import` it can be imported into projects using cocoa pods with the `use_frameworks!` option set.

There is also an issue with extending `CMObject#initWithCoder`. Since `CMObject#initWithObjectId` is the only designated initializer in Swift `CMObject#initWithCoder` becomes a convenience initializer and cannot call `super.initWithCoder()`. This makes extending `CMObject` difficult in Swift. I made `CMObject#initWithCoder` a designated initializer and things became easy again. I'm not sure it's the best option since XCoder throws a warning up about calling `[self initWithObjectId]` in it but it works without any issues so far.

### CODE REVIEW

**Comment by ethanmick** [comment]
Thanks Nate, I'll take a look at this, this weekend and merge it in shortly!

**Comment by natevecc** [comment]
Actually you're going to have issues with it :disappointed:. It works in my swift project but in the cloudmine-ios project I get all sorts of errors if I try and build it. I'm looking at them now but have other work that's going to probably pull me away :-1: .

**Comment by natevecc** [comment]
Hey I got the libcloudmine target to build and work in my Swift project without any issues but the tests and universal framework are giving me linker errors and I don't feel like tackling those today. Let me know if you need anything else from me.

**Comment by ethanmick** [comment]
Don't worry about the Universal Framework, that's no longer used. We just build from libcloudmine.

**Comment by apbendi** [comment]
hey @natevecc, I want to make sure both of these issues gets resolved in our next point release, which shouldn't be too far down the road. Right now, this PR has merge conflicts, and I'd also like to see these two issues broken into two separate PRs, just for clarity for someone looking at the history in the future.

I'm happy to work on getting the changes up to date and in two new PRs myself, but I also wanted to give you the opportunity. Didn't want to make it seem like I'm closing your PR and then making your exact changes in my own! Let me know if you want to take a stab or if you're cool with me doing it. Thanks again for the feedback :ok_hand:

**Comment by apbendi** [comment]
hey @natevecc, check out #62 and #63, which should address the issues you previously touched on here. Should get these merged soon at which point we'd **love** you to give the `develop` branch a shot with your application to see if it works as expected. Thanks again for bringing these to our attention and your help addressing them!

**Comment by apbendi** [comment]
hey @natevecc, with #62 and #63 merged on the `develop` branch, both of the issues you called our attention to here should be resolved. I'm going to suggest @geoffrey-young close this issue out.

If you have the time, we'd still love for you to give this new branch a try with your existing project, to see if it resolves your problems. Thanks again for pointing theses issues out!

**Pull request closed without merging**
